# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            # Change to the correct working directory
            cd /home/ec2-user/FoodWise
            
            git pull
            
            # Update your Node.js application
            npm install

            # Restart SC365.service
            sudo systemctl restart FoodWise.service
            sudo systemctl daemon-reload

            # Restart Nginx to apply changes
            sudo systemctl restart nginx
